// <auto-generated />
namespace Hbs.Web.QuestionAnswer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletingmodifiedby : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletingmodifiedby));
        
        string IMigrationMetadata.Id
        {
            get { return "201701271450309_deletingmodifiedby"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
